"""Sprint D Gates D1.0/D1.1 -- Lease-Level contracts.

Restates
``docs/plans/2026-09-04-anchor-lease-level-underwriting-d0-architecture.md``
Section 4 (Domain Contracts) exactly; that document governs on any
discrepancy. Like ``anchor.engine.contracts``, this module performs no
calculation and no I/O of its own -- it only describes the shape of a
Lease-Level deal's inputs.

These are vocabulary and invariants only. Nothing here computes anything: a
monthly rent, an annual aggregate, a rollover, an NOI and a return all belong
to D1.2 (base-rent timeline), D1.3 (property aggregation) and later phases.
``ModelMonth`` (D1.1) describes one canonical month but is built solely by
``anchor.leasing.calendar.build_model_months``.

The three entities mirror the D0 entity decisions (Section 4.1):

- ``LeaseLevelPropertyInputs`` -- a small scalar record, not an entity graph.
- ``Suite`` -- a first-class entity. A suite persists across leases; it is
  what rolls over (D2), what sits vacant, and what will carry a market-rent
  override (D2).
- ``Lease`` -- a first-class entity, separate from ``Suite``. One suite has
  many leases over time.

There is deliberately **no** ``Tenant`` entity (Section 4.1): a tenant matters
financially only via credit and multi-suite rollup, neither of which is in
competition scope, and a merged Tenant/Lease entity could not represent the
speculative successor lease the D2 rollover engine creates with no known
tenant. ``Lease.tenant_name`` is nullable precisely for that reason.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from enum import StrEnum


class EscalationBasis(StrEnum):
    """When a lease's contractual escalation applies (D0 Section 6.2).

    ``LEASE_ANNIVERSARY`` means each 12-month anniversary of **rent
    commencement** -- never of the analysis start and never of the calendar
    year. Acquisition does not reset a lease's escalation clock, so an
    in-place lease acquired midway through its term stays on its correct
    contractual step.

    D1 supports exactly these two members. ``CALENDAR_YEAR`` and fixed
    ``$/SF`` bumps are documented D2+ additive extensions (D0 Section 6.6);
    neither is declared here, so neither can be constructed or silently
    assumed.
    """

    NONE = "none"
    LEASE_ANNIVERSARY = "lease_anniversary"


class LeaseType(StrEnum):
    """The lease's expense-recovery structure (D0 Section 16.1).

    **Captured in D1, economically inert until D3.** It is required in D1
    rather than deferred so the analyst confronts it once, with the document
    in hand, rather than having it inferred later (D0 Section 20).
    """

    NNN = "nnn"
    GROSS = "gross"
    MODIFIED_GROSS = "modified_gross"


class LeaseOrigin(StrEnum):
    """Whether a lease was supplied by the analyst or generated by rollover
    (D0 Section 4.4).

    ``IN_PLACE`` is an actual lease off the rent roll -- a contractual fact.
    ``SUCCESSOR`` is a lease the D2 rollover engine created to model what
    happens after an in-place lease expires. It is an **underwriting
    assumption**, not a signed future tenancy, and D0 Section 8.4 makes two
    consequences mandatory: its ``tenant_name`` is ``None``, and no interface
    may present it as a known tenant (failure mode FM-D2-18).

    Declared at D2.2, the first gate that can actually construct a successor.
    D1 had no mechanism to produce one, so ``SUCCESSOR`` was a financially
    impossible state there and the field was deliberately withheld.

    ``Lease.origin`` defaults to ``IN_PLACE``, so every D1 call site
    constructs an identical lease and no D1 economics move.
    """

    IN_PLACE = "in_place"
    SUCCESSOR = "successor"


class LeasingCommissionMethod(StrEnum):
    """How a leasing commission is computed (D0 Section 12.3).

    **Exactly one member in D2**, and that is deliberate. Institutional
    practice genuinely varies -- percentage of total contractual base rent,
    percentage of first-year rent, stepped percentages by lease year, ``$/SF``
    -- so Anchor picks one, says which, and does not claim it is universal
    (D0 Section 12.1).

    ``PCT_OF_TOTAL_CONTRACTUAL_BASE_RENT`` is that choice: a percentage of the
    successor's total contractual base rent over its **full** term, including
    escalations, gross of free rent, untruncated by the hold horizon
    (D2 Section 8.3).

    **The method lives on ``MarketLeasingAssumptions``, never on ``Lease``.**
    That placement is the extension seam: adding ``PER_SF`` or
    ``PCT_OF_FIRST_YEAR_RENT`` later means one enum member plus the rate fields
    it needs on the assumptions record -- no change to the ``Lease`` contract,
    no change to any lease schedule, and no migration of lease data. D2
    implements one method; the seam exists so a second never requires replacing
    the lease contract.
    """

    PCT_OF_TOTAL_CONTRACTUAL_BASE_RENT = "pct_of_total_contractual_base_rent"


class RecoveryBasis(StrEnum):
    """How a Modified Gross lease's recovery threshold is expressed (D3.2).

    **Exactly one member in D3**, and that is deliberate -- it is an extension
    seam, not evidence that more methods should be added now (D3 conventions
    Section 6.2, HD-D3-3).

    ``EXPENSE_STOP_PSF`` is an explicit contractual expense stop in
    **``$/SF/YEAR``**, held on ``Lease.expense_stop_psf``. It was chosen over a
    calendar base year because a true base year needs the historical actual
    expenses of a year that predates the acquisition -- data Anchor does not
    possess -- and supporting one would tempt exactly the Hold-Year-1
    substitution D3 Section 6.1 forbids.

    A base-year amount is **reserved** as the enum's second member, to be added
    only if a competition rent roll forces it *and* the history it needs can be
    sourced. Adding it costs one member plus one nullable field, with no change
    to any other ``Lease`` field and no migration -- the same seam idiom
    ``LeasingCommissionMethod`` uses.
    """

    EXPENSE_STOP_PSF = "expense_stop_psf"


@dataclass(frozen=True, slots=True, kw_only=True)
class ModelMonth:
    """One canonical monthly period of the Lease-Level projection
    (D0 Section 4.7).

    Carries **both** identities so a monthly figure can be audited against a
    real calendar without re-deriving it from array position -- the guarantee
    guardrail G-M9 enforces and failure mode FM-4 exists to catch.

    ``period_index`` is the 1-based sequential model month: Month 1 is the
    calendar month containing ``analysis_start_date``. Zero-based financial
    period numbering is deliberately never exposed.

    ``month_start`` is the first calendar day of that month -- a plain
    ``date``, never a timestamp, never timezone-aware, never a display label.
    Presentation such as "Jan-27" belongs to the frontend.

    ``hold_year`` is derived from ``period_index``, never from the calendar
    year: ``((period_index - 1) // 12) + 1``. With an analysis start of
    2027-07-01, Hold Year 1 runs Jul-2027 through Jun-2028. The twelve forward
    exit months carry ``hold_year == H + 1``.

    ``is_forward_exit_month`` marks the twelve months ``12H+1 .. 12H+12`` that
    form the forward exit-NOI window (D0 Section 17.1), so that window can be
    identified without being recomputed anywhere else.

    Built only by ``anchor.leasing.calendar.build_model_months``; like every
    other contract in this module it performs no calculation of its own.
    """

    period_index: int
    month_start: date
    hold_year: int
    is_forward_exit_month: bool


@dataclass(frozen=True, slots=True, kw_only=True)
class LeaseMonthlySchedule:
    """One lease's canonical monthly contractual base-rent series
    (D0 Section 4.7).

    ``months`` is the exact ``ModelMonth`` tuple the schedule was built
    against -- a reference to the one canonical timeline, never a second
    representation of it. Carrying it here is what makes every rent figure
    auditable to a real calendar month without the caller having to keep the
    two aligned by hand. ``contractual_base_rent[i]`` is the rent for
    ``months[i]``, and the two tuples always share a length.

    ``contractual_base_rent`` is **gross** contractual rent in dollars per
    month. In D1 nothing reduces it; from D2 it stays gross and free rent is
    reported as its own separate line, never netted into this one.

    ``first_rent_period`` / ``last_rent_period`` are the first and last
    canonical periods **within this schedule's window** in which the lease is
    contractually active, or ``None`` when the lease is active in no modeled
    month at all. They are defined by contractual activity, not by a non-zero
    figure: a zero-rent lease is active and reports real periods.

    Note the distinction from ``rent.lease_rent_periods``, which returns the
    lease's *raw, unclamped* periods -- possibly negative, possibly past the
    horizon. Those drive escalation; these describe the window.

    ``occupied_area`` (D1.3) is the square footage this lease occupies in each
    month: ``leased_area_sf`` while contractually active, ``0.0`` otherwise.
    It is **state**, not flow, so it is never summed across months. Crucially
    it is derived from contractual *activity*, never from rent dollars -- a
    zero-rent lease occupies its suite exactly like any other, which is why
    ``contractual_base_rent > 0`` must never be used as an occupancy test.

    The D2/D3 fields D0 lists on this contract -- ``free_rent``,
    ``expense_recoveries``, ``tenant_improvements``, ``leasing_commissions``,
    ``occupancy_factor`` -- are deliberately not declared yet, following the
    same rule applied to ``Lease``: a gate declares only what it can actually
    produce.

    Built only by ``anchor.leasing.rent.build_lease_monthly_schedule``; this
    dataclass performs no calculation of its own.
    """

    lease_id: str
    suite_id: str
    months: tuple[ModelMonth, ...]
    contractual_base_rent: tuple[float, ...]
    occupied_area: tuple[float, ...]
    first_rent_period: int | None
    last_rent_period: int | None

    def __post_init__(self) -> None:
        expected = len(self.months)
        for name, series in (
            ("contractual_base_rent", self.contractual_base_rent),
            ("occupied_area", self.occupied_area),
        ):
            if len(series) != expected:
                raise ValueError(
                    f"LeaseMonthlySchedule requires one {name} figure per "
                    f"model month; got {len(series)} for {expected} months."
                )


@dataclass(frozen=True, slots=True, kw_only=True)
class PropertyRentRollSchedule:
    """The canonical monthly property rent roll (D0 Section 4.7) -- the D1
    deliverable.

    One row per canonical month, for the whole property. ``months`` is the
    same ``ModelMonth`` tuple every constituent ``LeaseMonthlySchedule`` was
    built against: one timeline, shared by reference, never rebuilt per lease.

    ``lease_schedules`` is retained deliberately. Property rent in March is
    auditable back to the individual leases that produced it -- monthly
    schedules are first-class outputs, not scratch work discarded after
    aggregation (guardrail G-M1).

    **Flow.** ``contractual_base_rent`` is the property's gross contractual
    base rent per month, the deterministic sum of the lease-level figures.
    Annual totals are derived from this series by
    ``anchor.leasing.aggregation.aggregate_flow_to_annual`` and by nothing
    else -- there is no independent annual rent formula anywhere.

    **State.** ``occupied_area``, ``vacant_area`` and ``physical_occupancy``
    are point-in-time values. They are never summed across months; their
    annual forms are an explicit year-end snapshot or an explicit average
    (D0 Section 5.7). ``occupied + vacant == rentable_area_sf`` holds in every
    month.

    Deliberately absent: NOI, recoveries, other income, operating expenses,
    market rent, rollover, TI, LC, free rent, debt, and every return metric.
    None exists in D1.

    Built only by
    ``anchor.leasing.aggregation.build_property_rent_roll_schedule``; this
    dataclass performs no calculation of its own.
    """

    months: tuple[ModelMonth, ...]
    lease_schedules: tuple[LeaseMonthlySchedule, ...]
    contractual_base_rent: tuple[float, ...]
    occupied_area: tuple[float, ...]
    vacant_area: tuple[float, ...]
    physical_occupancy: tuple[float, ...]

    def __post_init__(self) -> None:
        expected = len(self.months)
        for name, series in (
            ("contractual_base_rent", self.contractual_base_rent),
            ("occupied_area", self.occupied_area),
            ("vacant_area", self.vacant_area),
            ("physical_occupancy", self.physical_occupancy),
        ):
            if len(series) != expected:
                raise ValueError(
                    f"PropertyRentRollSchedule requires one {name} figure per "
                    f"model month; got {len(series)} for {expected} months."
                )
        for schedule in self.lease_schedules:
            if schedule.months != self.months:
                raise ValueError(
                    f"lease schedule {schedule.lease_id!r} was built against a "
                    "different month sequence; every schedule in a property "
                    "rent roll must share one canonical timeline."
                )


@dataclass(frozen=True, slots=True, kw_only=True)
class MarketLeasingAssumptions:
    """Market leasing assumptions for space that is available or rolling over
    (D0 Section 4.5).

    Property-level default, optionally overridden per suite (D0 Section 7.1).
    This record describes the **market**, not any signed lease: nothing here
    ever overrides a ``Lease``'s own contractual terms (D0 Section 24.4).
    Market assumptions apply only to successor leases the D2 rollover engine
    creates and to vacant suites being leased up.

    ``market_rent_psf`` is annual market rent per square foot (``$/SF/year``)
    **as of ``analysis_start_date``** -- it is the Month 1 market rent, not
    today's rent and not the rent at any rollover date. Domain ``>= 0``; zero
    is a real, computable market rent and is never reinterpreted as vacancy,
    missing data, or free rent.

    ``market_rent_growth`` is the **annual step** growth rate applied on
    ``analysis_start_date`` anniversaries (D0 Section 7.2). Domain ``> -1``,
    matching every other Anchor compounding rate, so a declining market is
    expressible.

    **The renewal-branch fields (D2.2).** ``renewal_rent_psf`` and
    ``renewal_rent_spread`` price a renewal successor, and D0 Section 24.3
    fixes their precedence: an explicit level wins, grown from
    ``analysis_start_date`` to the successor's commencement period; otherwise
    the successor prices at ``MarketRentPSF(c) * (1 + renewal_rent_spread)``.
    Both are measured on the **same temporal anchor as ``market_rent_psf``**,
    so the same input produces coherent economics whether a suite rolls in
    Year 2 or Year 5. ``renewal_rent_psf`` is nullable precisely because the
    spread form is the common one; ``None`` means "no explicit level was
    supplied", never "zero".

    ``renewal_term_months`` is the successor's term in **whole months**,
    domain ``>= 1``. It is never averaged, never rounded and never converted
    to years: under the approved composition (D2 HD-D2-1) each branch keeps
    its own integer term, so no fractional term can arise.

    ``successor_escalation_pct`` is the annual escalation **written into
    successor leases**. D2 Section 10 makes the distinction from
    ``market_rent_growth`` load-bearing: market growth prices the successor's
    *starting* rent once, at commencement; from there the successor is an
    ordinary contractual lease escalating on **its own** anniversaries. The
    two are different clocks and conflating them is failure mode FM-D2-14.

    **The new-tenant branch and the concession mechanics (D2.3).**
    ``new_term_months`` is the replacement tenant's term, in whole months,
    domain ``>= 1``. There is deliberately **no** ``new_rent_psf``: a new
    letting prices at ``MarketRentPSF(c)`` by definition, whereas a renewal is
    negotiated *relative* to market and therefore needs both an explicit level
    and a spread. D2 Section 12 records that asymmetry as correct rather than
    as a gap.

    ``new_downtime_months`` and ``renewal_downtime_months`` are the months the
    suite stands vacant after expiry before that branch's successor commences
    (D2 Section 6.1), domain ``>= 0``, fractional permitted. Renewal downtime
    is typically ``0.0`` -- a renewing tenant does not vacate -- but the field
    exists on both branches because an analyst may legitimately state a
    holdover gap, and because nothing is ever averaged between branches.

    ``new_free_rent_months`` and ``renewal_free_rent_months`` are full
    **month-equivalents of base-rent abatement**, domain ``>= 0``, fractional
    permitted (D2 Section 7.1). Free rent is a concession against base-rent
    *cash*; it never reduces contractual face rent and never makes occupied
    space vacant. Its upper bound is validated against the branch's own term
    and downtime (D2 Section 7.5).

    **The leasing costs (D2.4).** ``renewal_ti_psf`` and ``new_ti_psf`` are
    tenant-improvement allowances in ``$/SF``, domain ``>= 0``, multiplied by
    the successor's leased area and recorded in full at commencement.
    ``renewal_lc_pct`` and ``new_lc_pct`` are commission rates, domain
    ``0 <= x <= 1``, applied to the successor's **full-term contractual face
    rent**. ``leasing_commission_method`` names the basis and has exactly one
    member in D2 (D0 Section 12.3).

    Both are **below NOI** (D0 Sections 11 and 12.2): neither reduces rent,
    occupancy, EGI, NOI, DSCR or debt yield. Both are charged only on a
    rollover successor -- never on an in-place D1 lease, whose improvements and
    commission were funded by the seller before acquisition (failure mode
    FM-11).

    **The probability (D2.5).** ``renewal_probability`` is the probability the
    sitting tenant renews, domain ``0 <= p <= 1``. The new-tenant probability
    is deterministically ``1 - p`` and is deliberately **not** a second input:
    two fields could disagree, and the pair would then need a sums-to-one
    validation rule that this design makes unnecessary.

    It is the **only** weight in the model, and it weights **outcomes, never
    parameters** (D2 HD-D2-1). Every field above stays branch-specific and is
    read by exactly one branch; the probability is applied afterwards, to the
    completed monthly results. Nothing on this record is ever averaged with
    anything else on it.

    **This record now describes the complete D2 field set.** D0 Section 4.5's
    inventory is fully declared: rent and growth (D2.1), the renewal branch
    (D2.2), the new-tenant branch with downtime and free rent (D2.3), TI and LC
    (D2.4), and the probability (D2.5). Each arrived with the gate that could
    produce it, following this package's rule that **a gate declares only what
    it can actually produce** (see ``Lease`` and ``Suite`` below).

    The all-or-nothing override rule (D0 Section 24.2) is enforced
    structurally rather than by validation: every field is required and none
    carries a default, so a partially-populated override cannot be
    constructed at all. ``renewal_rent_psf`` is required *as a value* even
    though that value may be ``None`` -- the analyst states "no explicit
    renewal level" explicitly rather than by omission.
    """

    market_rent_psf: float
    market_rent_growth: float
    renewal_rent_psf: float | None
    renewal_rent_spread: float
    renewal_term_months: int
    successor_escalation_pct: float
    renewal_downtime_months: float
    renewal_free_rent_months: float
    new_term_months: int
    new_downtime_months: float
    new_free_rent_months: float
    renewal_ti_psf: float
    new_ti_psf: float
    leasing_commission_method: LeasingCommissionMethod
    renewal_lc_pct: float
    new_lc_pct: float
    renewal_probability: float


class MarketAssumptionSource(StrEnum):
    """Which record supplied a suite's resolved market leasing assumptions
    (D0 Section 24.5).

    Exactly D0's two values. ``PROPERTY_DEFAULT`` means the suite declared no
    ``market_leasing_override``; ``SUITE_OVERRIDE`` means it did, and that
    record was used in full.

    Whether the suite's rent-level-only exception (D0 Section 24.1) also
    applied is carried separately on ``ResolvedMarketLeasing`` rather than
    folded in as a third member here, because it is an orthogonal fact: a
    suite may set ``Suite.market_rent_psf`` on top of *either* source, and
    collapsing the two into one label would make one of them unreadable.
    """

    PROPERTY_DEFAULT = "property_default"
    SUITE_OVERRIDE = "suite_override"


@dataclass(frozen=True, slots=True, kw_only=True)
class ResolvedMarketLeasing:
    """One suite's market leasing assumptions after precedence is applied
    (D0 Section 24.5).

    The resolver runs **once per suite** and its result is recorded, so an
    analyst can always answer "which assumption applied here, and where did
    it come from" from the output alone -- without re-running the resolver
    and without a second precedence implementation anywhere.

    ``assumptions`` is the resolved record. ``source`` names which record it
    came from. ``market_rent_psf_from_suite`` records whether the D0
    Section 24.1 rent-level exception fired -- that is, whether
    ``Suite.market_rent_psf`` supplied the rent level on top of ``source``.
    Together the two answer the provenance question exactly, for both the
    common case (override the rent level only) and the rare one (override the
    whole record).

    Produced only by ``anchor.leasing.market.resolve_market_leasing``; this
    dataclass performs no resolution and no calculation of its own.
    """

    suite_id: str
    assumptions: MarketLeasingAssumptions
    source: MarketAssumptionSource
    market_rent_psf_from_suite: bool


@dataclass(frozen=True, slots=True, kw_only=True)
class MarketRentSchedule:
    """One suite's canonical monthly market-rent series (D2.1).

    The authoritative answer to "what is the market rent of this space, in
    ``$/SF/year``, as of this month" for every canonical month -- and the
    **only** place that answer is computed. D2.2 and D2.3 price a successor by
    reading ``market_rent_psf`` at the successor's commencement period from
    this schedule (or by calling the same authoritative function that built
    it); there is deliberately no second market-rent formula for rollover.

    ``months`` is the exact ``ModelMonth`` tuple the schedule was built
    against -- a reference to the one canonical D1 timeline, never a second
    calendar. ``market_rent_psf[i]`` is the market rent for ``months[i]``, and
    the two tuples always share a length.

    ``market_rent_psf`` is a **rate**, in ``$/SF/year``, held flat within each
    12-period band and stepping on ``analysis_start_date`` anniversaries. It
    is emphatically **not** a dollar cash flow: nothing multiplies it by suite
    area or divides it by 12 at D2.1, because market rent is an assumption
    about available space, not income the property receives. Converting it to
    a successor's cash rent is D2.2/D2.3 work and requires a commencement
    period, a term, downtime and free rent -- none of which exist here.

    ``resolved`` carries the assumptions the series was built from together
    with their provenance, so a market rent in Month 40 is auditable back to
    the record that produced it.

    The monthly series is retained, never discarded after use: monthly is
    canonical in Lease-Level and is later user-facing (guardrail G-M1).

    Built only by ``anchor.leasing.market.build_market_rent_schedule``; this
    dataclass performs no calculation of its own.
    """

    suite_id: str
    resolved: ResolvedMarketLeasing
    months: tuple[ModelMonth, ...]
    market_rent_psf: tuple[float, ...]

    def __post_init__(self) -> None:
        if len(self.market_rent_psf) != len(self.months):
            raise ValueError(
                "MarketRentSchedule requires one market_rent_psf figure per "
                f"model month; got {len(self.market_rent_psf)} for "
                f"{len(self.months)} months."
            )


@dataclass(frozen=True, slots=True, kw_only=True)
class LeaseLevelPropertyInputs:
    """The property-level scalars a Lease-Level deal needs (D0 Section 4.2).

    ``analysis_start_date`` is the single anchor for month identity (D1.1)
    and, later, for market-rent growth (D2). It must be the **first day of a
    calendar month**: it is the origin of every month index, and a mid-month
    origin would make every subsequent month a mid-month band, silently
    converting D1's whole-month recognition into an unstated proration
    convention. That requirement is enforced by
    ``anchor.leasing.validation``, not by this dataclass -- consistent with
    every other Anchor contract, which describes shape and leaves domain
    rules to its validator.

    ``rentable_area_sf`` is the **total rentable (leasable) area represented
    by this rent roll** -- the area that can be leased to a tenant and that
    every ``Suite`` collectively accounts for. It is the denominator for
    physical occupancy (D1.3) and for the D1.3 area invariant
    ``occupied + vacant == rentable_area_sf``.

    It is explicitly **not** gross building area, gross floor area, an
    arbitrary property square footage, or building area inclusive of
    non-rentable common area. Anchor requires that
    ``sum(suite_area_sf) == rentable_area_sf`` exactly (D1 implementation
    clarification, ``anchor.leasing.validation``): every rentable square foot
    must be accounted for by a suite, and vacant space is represented as a
    ``Suite`` with no lease -- never as area left outside the suite schedule.
    Common area is therefore never inferred from a residual, because there is
    no residual.

    Deliberately absent: ``property_name``, ``address``, ``property_type``,
    ``year_built``. Those are ``DealContext``
    (``anchor.ingestion.contracts``) -- informational, never engine inputs.

    Deliberately absent: ``hold_period``. The hold period lives on
    ``AcquisitionTerms`` and is passed as a parameter to the D1.1/D1.3
    schedule builders, exactly as ``build_detailed_operating_projection``
    already receives it. Duplicating it here would create a second place for
    the same assumption to disagree with itself.
    """

    analysis_start_date: date
    rentable_area_sf: float


@dataclass(frozen=True, slots=True, kw_only=True)
class Suite:
    """One leasable space (D0 Section 4.3).

    ``suite_id`` is **financial**, not merely informational: it is the key
    binding a lease to the space that rolls over in D2, and the unit at which
    vacancy, downtime and occupancy are computed. A ``suite_id`` typo is a
    validation ERROR, not a cosmetic issue.

    ``suite_area_sf`` is this suite's **rentable (leasable) area**, in the
    same basis as ``LeaseLevelPropertyInputs.rentable_area_sf``, which the
    suites must sum to exactly. Deliberately out of scope for D1-D3: load
    factors, usable-versus-rentable area, common-area allocation, and
    partial-suite leasing. One suite is one leasable unit.

    A **vacant suite is a ``Suite`` with no lease covering a given month** --
    never a synthetic "vacant lease" row. A suite carrying no lease at all is
    valid in D1: it carries area, participates in rentable-area
    reconciliation, and contributes zero contractual base rent and its full
    area to vacancy. That is precisely how vacant space must be represented,
    rather than by omitting it from the rent roll.

    **Market-rent overrides (D2.1, additive).** Both fields default to
    ``None``, which means "inherit the property default", so every D1 call
    site constructs an identical ``Suite`` and no D1 economics move.

    ``market_rent_psf`` overrides the **rent level alone**, keeping every
    other market assumption from the property default. D0 Section 24.1 makes
    this the single deliberate exception to the all-or-nothing rule below,
    because overriding only the rent level -- better or worse space in an
    otherwise uniform building -- is the overwhelmingly common case. It is
    measured as of ``analysis_start_date``, exactly like the property default
    it replaces.

    ``market_leasing_override`` replaces the **entire**
    ``MarketLeasingAssumptions`` record. D0 Section 24.2: it is
    **all-or-nothing** -- when a suite supplies one, that record is used in
    full and no field falls through to the property default. A partial
    per-field merge would make "which value applied" unanswerable without
    re-running the resolver. This is the rarer case: a retail suite in an
    office building, whose growth and terms differ too, not just its rent.

    Precedence between the two, and against the property default, is
    D0 Section 24.1 and is implemented once in
    ``anchor.leasing.market.resolve_market_leasing``:

    ```
    market_leasing_override.market_rent_psf  >  market_rent_psf  >  property default
    ```

    Neither field is a contractual term. No market assumption ever overrides
    a ``Lease``'s own rent, escalation or dates (D0 Section 24.4); they apply
    only to successor leases the rollover engine creates and to vacant space
    being leased up.
    """

    suite_id: str
    suite_area_sf: float
    suite_label: str | None = None
    market_rent_psf: float | None = None
    market_leasing_override: MarketLeasingAssumptions | None = None


@dataclass(frozen=True, slots=True, kw_only=True)
class Lease:
    """One contractual lease on one suite (D0 Section 4.4).

    **Dates.** ``rent_commencement_date`` is the first date base rent is
    owed and must be the first day of a calendar month.
    ``lease_expiration_date`` is the **inclusive** last date base rent is
    owed and must be the last day of a calendar month; the month containing
    it is fully paid. ``lease_start_date`` is the possession date --
    informational only, never entering any economic calculation, and
    therefore deliberately **not** month-alignment-validated (D0
    Section 5.5).

    **Rent.** ``base_rent_psf`` is annual base rent per square foot
    (``$/SF/year``) **as of ``rent_commencement_date``** -- the single D1
    rent convention (D0 Section 6.3). A rent roll stating a total annual rent
    is normalized at the analyst-approval boundary
    (``base_rent_psf = annual_rent / leased_area_sf``), never inside the
    engine, so there is exactly one rent representation and one code path.

    **Escalation.** ``escalation_pct`` is a fixed annual rate and
    ``escalation_basis`` says whether and from when it applies. Together with
    ``rent_commencement_date`` they carry everything D1.2 needs to compute
    escalation from the lease's **true contractual chronology**: the raw,
    unclamped commencement date is retained here, so an in-place lease
    commenced before ``analysis_start_date`` can be placed on its correct
    contractual step rather than restarted at step zero.

    **``leased_area_sf``** must equal the suite's ``suite_area_sf`` in D1-D3
    (D0 Section 4.4.1) -- one suite is one leasable unit, and a physically
    subdivided suite is modeled as two ``Suite`` rows. It is nonetheless kept
    as an explicit field because it is what a rent roll states and what rent
    and (later) TI are computed from; relaxing the equality later is then a
    validation change rather than a contract change.

    **Escalation coherence.** ``escalation_basis = NONE`` means the rent
    never steps, so ``escalation_pct`` must be exactly ``0.0``. A non-zero
    percentage paired with ``NONE`` is a validation ERROR rather than a
    silently ignored value: the two readings ("flat" versus "3% that someone
    forgot to switch on") differ materially, and Anchor does not guess which
    the analyst meant.

    **``origin`` (D2.2, additive).** D0 Section 4.4 marks it *derived* and
    phases it to D2. It defaults to ``LeaseOrigin.IN_PLACE``, so every D1 call
    site constructs an identical lease and no D1 economics move.
    ``SUCCESSOR`` marks a lease the rollover engine generated: an underwriting
    assumption about what follows an expiry, never a signed future tenancy.
    D0 Section 8.4 requires such a lease to carry ``tenant_name is None``, and
    ``anchor.leasing.validation`` enforces that pairing.

    A successor is otherwise **an ordinary contractual lease**. That is the
    point: from its commencement it prices and escalates through exactly the
    D1 formula in ``rent.py`` on its own contractual chronology (D2
    Section 10), so there is one contractual-rent engine in the package and
    the rollover gate reimplements nothing.

    **``recovery_basis`` and ``expense_stop_psf`` (D3.2, additive).** Both
    default to ``None``, so every D1 and D2 call site constructs an identical
    lease and no earlier economics move. They carry a `MODIFIED_GROSS` lease's
    **explicit** contractual recovery threshold, which Anchor never infers: a
    base year or expense stop is a contract term that predates the acquisition,
    while the buyer's first hold year is an artifact of when they bought, and
    substituting one for the other would change recovery on every Modified
    Gross lease in a rent roll (D3 Section 6.1).

    ``expense_stop_psf`` is in **``$/SF/YEAR``**, domain ``>= 0``, and is
    **nominally fixed** for the life of the lease: it does not grow with
    expense growth, market growth or contractual escalation, and does not reset
    annually or at acquisition (D3 Section 6.3, HD-D3-4).

    The two fields belong to `MODIFIED_GROSS` alone. A stop on an `NNN` or
    `GROSS` lease is a validation **ERROR** rather than a silently ignored
    value, because *a stop implies Modified Gross* -- allowing one elsewhere
    would make ``lease_type`` unreliable as an economic discriminator (D3
    Section 5.2).

    **Deliberately still not declared**: ``free_rent_months`` (D2.3), which
    waits for the gate that can produce it.
    """

    lease_id: str
    suite_id: str
    leased_area_sf: float
    rent_commencement_date: date
    lease_expiration_date: date
    base_rent_psf: float
    escalation_pct: float
    escalation_basis: EscalationBasis
    lease_type: LeaseType
    tenant_name: str | None = None
    lease_start_date: date | None = None
    origin: LeaseOrigin = LeaseOrigin.IN_PLACE
    recovery_basis: RecoveryBasis | None = None
    expense_stop_psf: float | None = None


@dataclass(frozen=True, slots=True, kw_only=True)
class RenewalBranch:
    """One suite's complete **pure renewal** scenario across the canonical
    timeline (D2.2, extended at D2.3).

    Under the approved composition (D2 HD-D2-1 / Section 4.2) a rollover is
    modelled as two independent, complete branch schedules that are weighted
    only at the monthly **output** level. This is the renewal branch: the
    deterministic answer to "what happens if this tenant renews, with
    certainty". It is conceptually the ``p = 1`` endpoint, but **no
    probability exists at D2.3** -- the weight arrives at D2.5, where this
    branch must be reproduced bit-identically by setting ``p = 1``.

    **D2.3 added downtime and free rent to this branch.** With
    ``downtime_months = 0.0`` and ``free_rent_months = 0.0`` every series below
    reduces to the accepted D2.2 pure-renewal result exactly: ``c`` is
    ``e + 1``, every ``successor_occupancy_factor`` inside the successor term
    is ``1.0``, every ``cash_rent_factor`` is ``1.0``, and ``cash_base_rent``
    equals ``contractual_base_rent``. D2.2's meaning is unchanged; D2.3 only
    made the zero case expressible as a value rather than as an absence.

    **Component assumptions are preserved verbatim** (D0 Section 8.4), never
    overwritten by the result they produced, so "which assumption produced
    this rollover, and where did it come from" is answerable from the output
    alone.

    **The two schedules stay separate and authoritative.**
    ``expiring_schedule`` is the in-place lease's own D1 schedule, reused
    unchanged -- D2 never recomputes an existing lease's contractual rent and
    never lets a market assumption touch it (D0 Section 24.4).
    ``successor_schedule`` is the successor's D1 schedule, built by the same
    ``rent.build_lease_monthly_schedule``.

    **Face rent and cash rent are separate series, and both are kept.**
    ``contractual_base_rent`` is **gross contractual face rent** -- the sum of
    the two schedules, reduced by neither downtime nor free rent. D2.4's LC
    basis reads it and must not see a concession (failure modes FM-D2-10,
    FM-D2-11b). ``cash_base_rent`` is what the property actually collects, and
    ``free_rent`` is the abatement on its own line, never netted into face
    rent.

    **Occupancy here is genuine, integral, branch physical occupancy** and
    keeps that name (D2 HD-D2-2's binding naming restriction). Within this
    scenario the suite is either occupied or it is not. The fractional
    ``successor_occupancy_factor`` is a **different quantity under a different
    name**: a month-equivalent rent-eligibility fraction, never a claim that
    part of a suite exists. The composed, possibly-fractional
    ``expected_occupied_area_sf`` / ``expected_occupancy`` series belongs to
    D2.5 and may never carry the ``physical_occupancy`` name either.

    **Horizon fields are untruncated.** ``successor_expiration_period`` is the
    successor's true contractual last period even when it lies beyond the
    projection. The monthly series stop at the canonical horizon (D0
    Section 8.6), but the contractual term is a real obligation and is
    preserved -- D2.4's LC basis needs the full term (failure mode FM-D2-11).


    **Leasing costs are below NOI and never touch the rent or occupancy series
    above** (D0 Sections 11 and 12.2, D2 Section 8). ``tenant_improvements``
    and ``leasing_commissions`` are monthly dollar series aligned 1:1 with the
    canonical timeline and are zero in every period except the successor's
    commencement, where each carries its full amount. When the successor
    commences beyond the projection they are zero throughout -- the timeline is
    never extended to display an event.

    ``full_term_contractual_face_rent`` is the LC basis: the successor's total
    contractual face rent over its **entire** term, including escalations,
    gross of free rent, untruncated by the hold horizon, and unreduced by the
    fractional first month that downtime creates. It is retained because it
    can depend on contractual months lying beyond the visible projection, so
    the commission is otherwise unauditable from the schedule alone.

    Built only by ``anchor.leasing.rollover.build_renewal_branch``; this
    dataclass performs no calculation of its own.
    """

    suite_id: str
    expiring_lease_id: str
    successor_lease_id: str
    expiration_period: int
    commencement_period: int
    successor_expiration_period: int
    commences_within_projection: bool

    # --- component assumptions, preserved verbatim (D0 Section 8.4) ---
    resolved: ResolvedMarketLeasing
    market_rent_psf_at_commencement: float
    renewal_rent_psf: float | None
    renewal_rent_spread: float
    starting_rent_psf: float
    term_months: int
    successor_escalation_pct: float
    downtime_months: float
    free_rent_months: float

    # --- the two authoritative schedules ---
    successor_lease: Lease
    months: tuple[ModelMonth, ...]
    expiring_schedule: LeaseMonthlySchedule
    successor_schedule: LeaseMonthlySchedule

    # --- face rent (gross), then the concession waterfall, then cash ---
    contractual_base_rent: tuple[float, ...]
    successor_occupancy_factor: tuple[float, ...]
    free_rent_abatement_months: tuple[float, ...]
    cash_rent_factor: tuple[float, ...]
    free_rent: tuple[float, ...]
    cash_base_rent: tuple[float, ...]

    # --- integral branch physical state ---
    occupied_area: tuple[float, ...]
    physical_occupancy: tuple[float, ...]

    # --- leasing costs, below NOI (D2.4) ---
    ti_psf: float
    lc_pct: float
    leasing_commission_method: LeasingCommissionMethod
    full_term_contractual_face_rent: float
    tenant_improvement_amount: float
    leasing_commission_amount: float
    tenant_improvements: tuple[float, ...]
    leasing_commissions: tuple[float, ...]

    def __post_init__(self) -> None:
        expected = len(self.months)
        for name, series in (
            ("contractual_base_rent", self.contractual_base_rent),
            ("successor_occupancy_factor", self.successor_occupancy_factor),
            ("free_rent_abatement_months", self.free_rent_abatement_months),
            ("cash_rent_factor", self.cash_rent_factor),
            ("free_rent", self.free_rent),
            ("cash_base_rent", self.cash_base_rent),
            ("occupied_area", self.occupied_area),
            ("physical_occupancy", self.physical_occupancy),
            ("tenant_improvements", self.tenant_improvements),
            ("leasing_commissions", self.leasing_commissions),
        ):
            if len(series) != expected:
                raise ValueError(
                    f"RenewalBranch requires one {name} figure per model month; "
                    f"got {len(series)} for {expected} months."
                )
        for label, schedule in (
            ("expiring", self.expiring_schedule),
            ("successor", self.successor_schedule),
        ):
            if schedule.months != self.months:
                raise ValueError(
                    f"the {label} schedule was built against a different "
                    "month sequence; a renewal branch must share one canonical "
                    "timeline."
                )


@dataclass(frozen=True, slots=True, kw_only=True)
class NewTenantBranch:
    """One suite's complete **pure new-tenant** scenario across the canonical
    timeline (D2.3).

    The other branch of the approved composition (D2 HD-D2-1 / Section 4.2):
    the deterministic answer to "what happens if this tenant does *not* renew,
    with certainty". It is conceptually the ``p = 0`` endpoint, but **no
    probability exists at D2.3** -- D2.5 must reproduce this branch
    bit-identically by setting ``p = 0``.

    **Every series carries the same name and the same meaning as on
    ``RenewalBranch``.** That is deliberate: D2.5 weights the two branches
    month by month, and a composition layer that had to translate between two
    shapes would be a place for the branches to disagree. The two differ in
    exactly one economic respect -- how the successor's starting rent is
    priced -- and in the assumption fields that pricing reads.

    **A new letting prices at market, by definition.** There is no
    ``new_rent_psf`` field and no new-tenant spread: ``starting_rent_psf`` is
    ``MarketRentPSF(c)`` at the successor's commencement period, read from the
    canonical D2.1 schedule. A renewal is negotiated *relative* to market and
    therefore carries both an explicit level and a spread; a new letting *is*
    market. D2 Section 12 records that asymmetry as correct rather than as a
    gap.

    **Downtime is this branch's characteristic mechanic.** The suite stands
    physically vacant for ``floor(downtime_months)`` full periods after expiry;
    the successor commences at ``c = e + 1 + floor(D)`` and recognises
    ``1 - frac(D)`` of that first month's rent (D2 Section 6.1). Total rent
    forgone is exactly ``D`` month-equivalents.

    Face rent, cash rent, the free-rent waterfall, integral branch physical
    occupancy and the untruncated horizon fields all carry the meanings
    documented on ``RenewalBranch``.


    **Leasing costs are below NOI and never touch the rent or occupancy series
    above** (D0 Sections 11 and 12.2, D2 Section 8). ``tenant_improvements``
    and ``leasing_commissions`` are monthly dollar series aligned 1:1 with the
    canonical timeline and are zero in every period except the successor's
    commencement, where each carries its full amount. When the successor
    commences beyond the projection they are zero throughout -- the timeline is
    never extended to display an event.

    ``full_term_contractual_face_rent`` is the LC basis: the successor's total
    contractual face rent over its **entire** term, including escalations,
    gross of free rent, untruncated by the hold horizon, and unreduced by the
    fractional first month that downtime creates. It is retained because it
    can depend on contractual months lying beyond the visible projection, so
    the commission is otherwise unauditable from the schedule alone.

    Built only by ``anchor.leasing.rollover.build_new_tenant_branch``; this
    dataclass performs no calculation of its own.
    """

    suite_id: str
    expiring_lease_id: str
    successor_lease_id: str
    expiration_period: int
    commencement_period: int
    successor_expiration_period: int
    commences_within_projection: bool

    # --- component assumptions, preserved verbatim (D0 Section 8.4) ---
    resolved: ResolvedMarketLeasing
    market_rent_psf_at_commencement: float
    starting_rent_psf: float
    term_months: int
    successor_escalation_pct: float
    downtime_months: float
    free_rent_months: float

    # --- the two authoritative schedules ---
    successor_lease: Lease
    months: tuple[ModelMonth, ...]
    expiring_schedule: LeaseMonthlySchedule
    successor_schedule: LeaseMonthlySchedule

    # --- face rent (gross), then the concession waterfall, then cash ---
    contractual_base_rent: tuple[float, ...]
    successor_occupancy_factor: tuple[float, ...]
    free_rent_abatement_months: tuple[float, ...]
    cash_rent_factor: tuple[float, ...]
    free_rent: tuple[float, ...]
    cash_base_rent: tuple[float, ...]

    # --- integral branch physical state ---
    occupied_area: tuple[float, ...]
    physical_occupancy: tuple[float, ...]

    # --- leasing costs, below NOI (D2.4) ---
    ti_psf: float
    lc_pct: float
    leasing_commission_method: LeasingCommissionMethod
    full_term_contractual_face_rent: float
    tenant_improvement_amount: float
    leasing_commission_amount: float
    tenant_improvements: tuple[float, ...]
    leasing_commissions: tuple[float, ...]

    def __post_init__(self) -> None:
        expected = len(self.months)
        for name, series in (
            ("contractual_base_rent", self.contractual_base_rent),
            ("successor_occupancy_factor", self.successor_occupancy_factor),
            ("free_rent_abatement_months", self.free_rent_abatement_months),
            ("cash_rent_factor", self.cash_rent_factor),
            ("free_rent", self.free_rent),
            ("cash_base_rent", self.cash_base_rent),
            ("occupied_area", self.occupied_area),
            ("physical_occupancy", self.physical_occupancy),
            ("tenant_improvements", self.tenant_improvements),
            ("leasing_commissions", self.leasing_commissions),
        ):
            if len(series) != expected:
                raise ValueError(
                    f"NewTenantBranch requires one {name} figure per model month; "
                    f"got {len(series)} for {expected} months."
                )
        for label, schedule in (
            ("expiring", self.expiring_schedule),
            ("successor", self.successor_schedule),
        ):
            if schedule.months != self.months:
                raise ValueError(
                    f"the {label} schedule was built against a different "
                    "month sequence; a new-tenant branch must share one canonical "
                    "timeline."
                )


@dataclass(frozen=True, slots=True, kw_only=True)
class ExpectedRollover:
    """The probability-weighted expected economics of one suite's rollover
    (D2.5).

    **The third layer, and it replaces neither branch.** D2 HD-D2-1 approves
    weighting *outcomes*, not parameters: each branch is calculated
    independently and completely first, and the weight is applied last, to the
    finished monthly results. Both branches are retained here in full, so
    "which assumption produced this, and what did each scenario actually do"
    stays answerable from the output alone.

    ```
    Expected[m] = p * Renewal[m] + (1 - p) * NewTenant[m]
    ```

    **This is an expected-value underwriting output, not a lease.** There is
    deliberately **no** successor ``Lease`` field on this contract and no
    synthetic expected lease anywhere: at ``p = 0.65`` the expectation
    corresponds to no single real-world outcome, pays a rent no actual tenant
    would pay, and would have an expiration belonging to neither scenario. Each
    branch keeps its own term, its own commencement and its own expiration
    (D2 Section 1.3: a weighted term is not a term).

    **Every dollar series is weighted from the corresponding branch dollar
    series, directly.** None is reconstructed from weighted factors, because
    ``E[X * Y] != E[X] * E[Y]`` whenever the two are branch-correlated -- which
    they always are here. Reconstructing expected cash as
    ``expected face * expected cash factor`` is precisely the error that
    invalidated the rejected weighted-parameter method (D2 Section 1.3), and it
    understates or overstates every month in which the branches differ in
    timing.

    **The occupancy naming is binding** (D2 HD-D2-2). Each branch keeps a
    genuine, integral ``physical_occupancy``; the composed series here may be
    fractional and is therefore named ``expected_occupancy`` and
    ``expected_occupied_area_sf``. A fractional series must never carry the
    physical name (failure mode FM-D2-19): 65% of a suite is not literally
    occupied, and reporting it as though it were is dishonest in a way the
    expected framing is not.

    **Three occupancy-like series, deliberately distinct:**

    - ``expected_occupancy`` -- weighted *physical* state. In a month where the
      renewal branch is in possession and the new-tenant branch is still dark,
      this is ``p``.
    - ``expected_successor_occupancy_factor`` -- weighted *month-equivalent
      rent eligibility*. It differs from the above whenever a branch is in a
      fractional downtime-boundary month, where the suite is physically
      occupied but only part of the month's rent is recognised.
    - ``expected_cash_rent_factor`` -- weighted cash eligibility after free
      rent. **Descriptive only.** It must never be multiplied by an expected
      face rent to reconstruct expected cash.

    ``expected_free_rent_abatement_months`` is descriptive in the same way and
    under the same prohibition.

    **Timing is never weighted.** No expected commencement, expiration, term or
    downtime exists. Where the two branches place a one-time cost in different
    months, the expected series carries **two** weighted events at their real
    scenario months -- never one event at a synthetic intermediate date.

    **One rollover only.** Each branch's first successor is composed as it
    stands; a branch whose successor has already expired simply contributes its
    own post-expiration values. Continuing the chain is D2.6's subject
    (D2 HD-D2-3).

    Built only by ``anchor.leasing.rollover.compose_expected_rollover``; this
    dataclass performs no calculation of its own.
    """

    suite_id: str
    expiring_lease_id: str
    renewal_probability: float
    months: tuple[ModelMonth, ...]

    # --- both complete branches, retained in full (D2 HD-D2-1) ---
    renewal_branch: RenewalBranch
    new_tenant_branch: NewTenantBranch

    # --- expected monthly dollars, each weighted from branch dollars ---
    expected_contractual_base_rent: tuple[float, ...]
    expected_cash_base_rent: tuple[float, ...]
    expected_free_rent: tuple[float, ...]
    expected_tenant_improvements: tuple[float, ...]
    expected_leasing_commissions: tuple[float, ...]

    # --- expected occupancy, fractional and named accordingly ---
    expected_occupied_area_sf: tuple[float, ...]
    expected_occupancy: tuple[float, ...]
    expected_vacant_area_sf: tuple[float, ...]
    expected_vacancy: tuple[float, ...]

    # --- descriptive expected factors; never a route back to dollars ---
    expected_successor_occupancy_factor: tuple[float, ...]
    expected_free_rent_abatement_months: tuple[float, ...]
    expected_cash_rent_factor: tuple[float, ...]

    # --- expected one-time cost totals (D2 Section 8.4) ---
    expected_tenant_improvement_amount: float
    expected_leasing_commission_amount: float

    def __post_init__(self) -> None:
        expected = len(self.months)
        for name, series in (
            ("expected_contractual_base_rent", self.expected_contractual_base_rent),
            ("expected_cash_base_rent", self.expected_cash_base_rent),
            ("expected_free_rent", self.expected_free_rent),
            ("expected_tenant_improvements", self.expected_tenant_improvements),
            ("expected_leasing_commissions", self.expected_leasing_commissions),
            ("expected_occupied_area_sf", self.expected_occupied_area_sf),
            ("expected_occupancy", self.expected_occupancy),
            ("expected_vacant_area_sf", self.expected_vacant_area_sf),
            ("expected_vacancy", self.expected_vacancy),
            (
                "expected_successor_occupancy_factor",
                self.expected_successor_occupancy_factor,
            ),
            (
                "expected_free_rent_abatement_months",
                self.expected_free_rent_abatement_months,
            ),
            ("expected_cash_rent_factor", self.expected_cash_rent_factor),
        ):
            if len(series) != expected:
                raise ValueError(
                    f"ExpectedRollover requires one {name} figure per model "
                    f"month; got {len(series)} for {expected} months."
                )
        for label, branch in (
            ("renewal", self.renewal_branch),
            ("new-tenant", self.new_tenant_branch),
        ):
            if branch.months != self.months:
                raise ValueError(
                    f"the {label} branch was built against a different month "
                    "sequence; an expected rollover must share one canonical "
                    "timeline."
                )


class RolloverBranchKind(StrEnum):
    """Which scenario a rollover transition represents (D2.6).

    Declared for **audit ordering and labelling only**. It never enters a
    calculation: each branch's economics come from its own fields on
    ``MarketLeasingAssumptions``, and no code selects a formula by inspecting
    this value.

    Member order is the documented transition-audit order: ``RENEWAL`` before
    ``NEW_TENANT``, matching the order the composition has used since D2.5.
    """

    RENEWAL = "renewal"
    NEW_TENANT = "new_tenant"


@dataclass(frozen=True, slots=True, kw_only=True)
class SuccessorContribution:
    """One successor's own economics, and **nothing else** (D2.6).

    **The anti-double-counting boundary.** ``RenewalBranch`` and
    ``NewTenantBranch`` carry full canonical series that include the expiring
    lease's history: four of their ten series -- ``contractual_base_rent``,
    ``cash_base_rent``, ``occupied_area`` and ``physical_occupancy`` -- mix it
    in. Adding a whole branch at every recursive event would re-count that
    history once per generation.

    This contract is the successor half alone. Every series below is zero in
    every period the successor is not contractually active, and in particular
    is zero in every period at or before ``parent_expiration_period``. The
    recursion accumulates ``probability mass x contribution`` and never a
    branch.

    **It is built from a rollover *state*, not from a predecessor ``Lease``.**
    The successor needs only the parent's expiration period, the suite, the
    chain-invariant lease type and the resolved assumptions -- which is exactly
    the D2 Section 5.5.1 sufficiency proof made structural. A predecessor's
    rent, escalation, concessions or identity cannot reach it, so two scenario
    paths arriving at the same expiration period produce identical
    contributions and their probability masses may be merged.

    ``successor_lease.lease_id`` is a derived label. It is deliberately not
    part of any state key and must never affect a number.

    Built only by ``anchor.leasing.rollover.build_successor_contribution``;
    this dataclass performs no calculation of its own.
    """

    branch: RolloverBranchKind
    suite_id: str
    parent_expiration_period: int
    commencement_period: int
    successor_expiration_period: int
    commences_within_projection: bool

    # --- the assumptions this transition used, preserved verbatim ---
    resolved: ResolvedMarketLeasing
    market_rent_psf_at_commencement: float
    starting_rent_psf: float
    term_months: int
    successor_escalation_pct: float
    downtime_months: float
    free_rent_months: float
    ti_psf: float
    lc_pct: float
    leasing_commission_method: LeasingCommissionMethod
    full_term_contractual_face_rent: float
    tenant_improvement_amount: float
    leasing_commission_amount: float

    successor_lease: Lease
    months: tuple[ModelMonth, ...]
    successor_schedule: LeaseMonthlySchedule

    # --- successor-only monthly series ---
    contractual_base_rent: tuple[float, ...]
    cash_base_rent: tuple[float, ...]
    free_rent: tuple[float, ...]
    tenant_improvements: tuple[float, ...]
    leasing_commissions: tuple[float, ...]
    occupied_area: tuple[float, ...]
    physical_occupancy: tuple[float, ...]
    successor_occupancy_factor: tuple[float, ...]
    free_rent_abatement_months: tuple[float, ...]
    cash_rent_factor: tuple[float, ...]

    def __post_init__(self) -> None:
        expected = len(self.months)
        for name, series in (
            ("contractual_base_rent", self.contractual_base_rent),
            ("cash_base_rent", self.cash_base_rent),
            ("free_rent", self.free_rent),
            ("tenant_improvements", self.tenant_improvements),
            ("leasing_commissions", self.leasing_commissions),
            ("occupied_area", self.occupied_area),
            ("physical_occupancy", self.physical_occupancy),
            ("successor_occupancy_factor", self.successor_occupancy_factor),
            ("free_rent_abatement_months", self.free_rent_abatement_months),
            ("cash_rent_factor", self.cash_rent_factor),
        ):
            if len(series) != expected:
                raise ValueError(
                    f"SuccessorContribution requires one {name} figure per "
                    f"model month; got {len(series)} for {expected} months."
                )
            # The primary anti-double-counting invariant: a successor may
            # never contribute to a period at or before its parent expired.
            for month, value in zip(self.months, series):
                if month.period_index <= self.parent_expiration_period and value != 0.0:
                    raise ValueError(
                        f"SuccessorContribution.{name} is non-zero in period "
                        f"{month.period_index}, at or before its parent "
                        f"expiration {self.parent_expiration_period}; a "
                        "successor contributes only to later periods."
                    )
        if self.successor_expiration_period <= self.parent_expiration_period:
            raise ValueError(
                f"successor expiration {self.successor_expiration_period} must "
                f"be strictly later than its parent's "
                f"{self.parent_expiration_period}; rollover time must advance."
            )


@dataclass(frozen=True, slots=True, kw_only=True)
class RolloverEventStateAudit:
    """One **merged** rollover-event state (D2.6, D2 Section 5.5).

    A state is "a lease on this suite expires at ``expiration_period``,
    carrying ``probability_mass``". One record per merged state, never one per
    scenario path: an explicit tree of `2^r` paths is exactly what the accepted
    architecture replaces, and storing one would defeat the point.

    ``probability_mass`` is the total mass of every path that reached this
    expiration period, accumulated deterministically. ``processed`` is ``True``
    when the state produced transitions; a state at or beyond the projection
    horizon is recorded but not processed, because any child would commence
    outside the window and contribute nothing.
    """

    expiration_period: int
    probability_mass: float
    processed: bool


@dataclass(frozen=True, slots=True, kw_only=True)
class RolloverTransitionAudit:
    """One parent-to-successor transition (D2.6).

    Bounded and financially useful: what the transition was, how likely, when
    it began and ended, what it priced at, and what it cost. Deliberately no
    monthly series -- those are already accumulated into the expected result,
    and duplicating them per transition would make the audit grow with the
    horizon for no additional answer.

    ``probability_mass`` is the child's own mass: the parent's mass times the
    branch probability. Masses of the two children of one parent sum exactly to
    the parent's.
    """

    parent_expiration_period: int
    branch: RolloverBranchKind
    probability_mass: float
    commencement_period: int
    successor_expiration_period: int
    commences_within_projection: bool
    starting_rent_psf: float
    term_months: int
    tenant_improvement_amount: float
    leasing_commission_amount: float


@dataclass(frozen=True, slots=True, kw_only=True)
class RecursiveRollover:
    """A suite's expected economics across **all** successor generations
    (D2.6).

    The D2 deliverable. Rollover recursion runs until the canonical projection
    ends and stops **only** there: there is no financial depth cap (HD-D2-3)
    and no computational cap of any kind (D2 Section 5.5.5), because the state
    count is structurally bounded by the horizon.

    **How it is computed** (D2 Section 5.5). Scenario probability mass is
    propagated over rollover-event states keyed by expiration period and
    processed in ascending order. Two paths reaching the same expiration period
    have identical futures -- a successor prices from market at its own
    commencement and never reads its predecessor's rent -- so their masses
    merge, and one state is processed once. Nothing but mass is ever combined:
    no rent, no term, no date, no rate.

    **The known lease contributes once, at mass 1.** Every period before the
    in-place lease expires is deterministic contractual history and is never
    probability-weighted. Each successor transition then contributes only its
    own economics, for periods strictly after its parent expired.

    **Expected dollar series weight dollars.** Face, cash, free rent, TI and LC
    each accumulate ``mass x that successor's own dollar series``. None is
    reconstructed from an expected face rent times an expected factor, which is
    the nonlinearity that invalidated the rejected weighted-parameter method
    (D2 Section 1.3). The three descriptive factor series are outputs only.

    **Occupancy naming is binding** (HD-D2-2). Each successor keeps a genuine
    integral ``physical_occupancy``; the accumulated series here may be
    fractional and is therefore ``expected_occupancy`` /
    ``expected_occupied_area_sf``.

    ``terminal_probability_mass`` is the mass that reached a state from which
    no further rollover can affect a canonical month. It reconciles to ``1``:
    mass is neither created nor destroyed by a split or a merge.

    Built only by ``anchor.leasing.rollover.build_recursive_rollover``; this
    dataclass performs no calculation of its own.
    """

    suite_id: str
    expiring_lease_id: str
    renewal_probability: float
    months: tuple[ModelMonth, ...]

    initial_lease: Lease
    initial_schedule: LeaseMonthlySchedule

    # --- expected monthly dollars ---
    expected_contractual_base_rent: tuple[float, ...]
    expected_cash_base_rent: tuple[float, ...]
    expected_free_rent: tuple[float, ...]
    expected_tenant_improvements: tuple[float, ...]
    expected_leasing_commissions: tuple[float, ...]

    # --- expected occupancy, fractional and named accordingly ---
    expected_occupied_area_sf: tuple[float, ...]
    expected_occupancy: tuple[float, ...]
    expected_vacant_area_sf: tuple[float, ...]
    expected_vacancy: tuple[float, ...]

    # --- descriptive expected factors; never a route back to dollars ---
    expected_successor_occupancy_factor: tuple[float, ...]
    expected_free_rent_abatement_months: tuple[float, ...]
    expected_cash_rent_factor: tuple[float, ...]

    # --- expected one-time totals ---
    expected_tenant_improvement_amount: float
    expected_leasing_commission_amount: float

    # --- bounded audit (D2 Section 5.5.5: <= N states, <= 2N transitions) ---
    event_states: tuple[RolloverEventStateAudit, ...]
    transitions: tuple[RolloverTransitionAudit, ...]
    terminal_probability_mass: float

    def __post_init__(self) -> None:
        expected = len(self.months)
        for name, series in (
            ("expected_contractual_base_rent", self.expected_contractual_base_rent),
            ("expected_cash_base_rent", self.expected_cash_base_rent),
            ("expected_free_rent", self.expected_free_rent),
            ("expected_tenant_improvements", self.expected_tenant_improvements),
            ("expected_leasing_commissions", self.expected_leasing_commissions),
            ("expected_occupied_area_sf", self.expected_occupied_area_sf),
            ("expected_occupancy", self.expected_occupancy),
            ("expected_vacant_area_sf", self.expected_vacant_area_sf),
            ("expected_vacancy", self.expected_vacancy),
            (
                "expected_successor_occupancy_factor",
                self.expected_successor_occupancy_factor,
            ),
            (
                "expected_free_rent_abatement_months",
                self.expected_free_rent_abatement_months,
            ),
            ("expected_cash_rent_factor", self.expected_cash_rent_factor),
        ):
            if len(series) != expected:
                raise ValueError(
                    f"RecursiveRollover requires one {name} figure per model "
                    f"month; got {len(series)} for {expected} months."
                )
        if self.initial_schedule.months != self.months:
            raise ValueError(
                "the initial lease schedule was built against a different "
                "month sequence; a recursive rollover must share one canonical "
                "timeline."
            )
        # Structural bounds from D2 Section 5.5.5. A violation is a bug in the
        # propagation, never a user-configurable limit.
        if len(self.event_states) > expected:
            raise ValueError(
                f"{len(self.event_states)} event states exceed the structural "
                f"bound of {expected}; expiration periods are integers in the "
                "canonical window, so states cannot outnumber months."
            )
        if len(self.transitions) > 2 * expected:
            raise ValueError(
                f"{len(self.transitions)} transitions exceed the structural "
                f"bound of {2 * expected}."
            )


@dataclass(frozen=True, slots=True, kw_only=True)
class RecoverableExpensePool:
    """The property's monthly recoverable operating expense, injected (D3.1).

    **This is the D3/D4 seam.** D3 answers "given the pool, what does the tenant
    reimburse"; it does **not** project operating expenses, convert the engine's
    annual figures to monthly, apply expense growth, or apply
    ``recoverable_expense_ratio``. D4 owns constructing this series from the
    authoritative operating projection (D3 conventions Section 3.4).

    ``recoverable_expenses[i]`` is the **total property operating expense
    dollars eligible for tenant recovery** in ``months[i]`` -- already net of
    everything the accepted convention excludes: the management fee, capital
    expenditures, TI, LC and debt service (D3 Section 3.3). D3 trusts that
    construction and deliberately cannot inspect it: the pool arrives as one
    figure per month with no category breakdown, so no code here can infer, or
    silently re-police, what went into it.

    Domain ``>= 0`` and finite. A negative pool would be an expense credit,
    which the accepted D3 model has no convention for, so it is refused rather
    than given an invented meaning.

    ``months`` is the exact ``ModelMonth`` tuple the pool was built against --
    a reference to the one canonical timeline, never a second calendar. Carrying
    it here is what lets a recovery schedule verify **month identity** rather
    than merely matching lengths, so a pool built for a different projection
    cannot be silently zipped against a lease.

    This contract performs no calculation of its own.
    """

    months: tuple[ModelMonth, ...]
    recoverable_expenses: tuple[float, ...]

    def __post_init__(self) -> None:
        if len(self.recoverable_expenses) != len(self.months):
            raise ValueError(
                "RecoverableExpensePool requires one recoverable_expenses "
                f"figure per model month; got "
                f"{len(self.recoverable_expenses)} for {len(self.months)} "
                "months."
            )


@dataclass(frozen=True, slots=True, kw_only=True)
class LeaseRecoverySchedule:
    """One lease's canonical monthly expense-recovery **revenue** (D3.1).

    **Recovery is revenue on its own line** (D0 Section 10.2, D3 Section 1.2).
    It is never a reduction to contractual base rent, never a reduction to
    property operating expenses, never a negative expense, and never a leasing
    cost. Nothing here is netted into anything.

    ``months`` is the exact canonical ``ModelMonth`` tuple, shared by reference
    with the pool and with the lease's own D1 schedule.

    ``tenant_pro_rata_share`` is ``leased_area_sf / rentable_area_sf`` on D1's
    exact rentable-area basis (D3 Section 4.1) -- a scalar, because neither area
    varies by month in D1-D3.

    ``economic_responsibility_factor`` is the fraction of each month for which
    this lease is economically responsible for expenses. For a known in-place
    lease it is ``1.0`` **only while contractually active** and ``0.0`` before
    commencement and after expiration; because D1 dates are month-aligned it is
    never fractional for such a lease (D3 Section 7.1). It is deliberately a
    separate concept from ``physical_occupancy``, which D2 HD-D2-2 binds to be
    an integral month-end *state*.

    ``tenant_recoverable_expense_share`` is ``share × pool`` -- the tenant's
    arithmetic share of the pool, before responsibility is applied. It is
    retained for audit and is reported even for a `GROSS` lease, where the
    tenant owes none of it: the share is a fact about area, the recovery is a
    fact about the lease.

    ``expense_recovery`` is what the lease actually owes: ``factor × share ×
    pool`` for `NNN`, exactly ``0.0`` for `GROSS`, and
    ``factor × max(0, share × pool − monthly stop)`` for `MODIFIED_GROSS`.

    **Four fields exist so a Modified Gross figure is auditable without
    reconstructing a hidden assumption** (D3.2). Each answers a distinct
    question:

    - ``recovery_basis`` and ``expense_stop_psf`` -- *which contractual
      threshold applied, and at what rate*. Both are ``None`` for `NNN` and
      `GROSS`, which carry no threshold at all.
    - ``monthly_expense_stop_dollars`` -- *the threshold in the units the
      comparison actually uses*: ``expense_stop_psf × leased_area_sf / 12``, a
      scalar because the stop is nominally fixed and the area does not vary.
      ``None`` where there is no stop.
    - ``full_month_expense_recovery`` -- *the obligation before responsibility
      was applied*. It makes the D3 Section 7.1.1 ordering visible: the factor
      scales this figure, and never the expense share inside the clip.

    ``full_month_expense_recovery`` is meaningful for every structure -- the
    tenant share for `NNN`, ``0.0`` for `GROSS`, the clipped excess for
    `MODIFIED_GROSS` -- so it is a series rather than a nullable, and carries no
    special case.

    Built only by ``anchor.leasing.recoveries.build_lease_recovery_schedule``;
    this dataclass performs no calculation of its own.
    """

    lease_id: str
    suite_id: str
    lease_type: LeaseType
    months: tuple[ModelMonth, ...]
    tenant_pro_rata_share: float
    recovery_basis: RecoveryBasis | None
    expense_stop_psf: float | None
    monthly_expense_stop_dollars: float | None
    economic_responsibility_factor: tuple[float, ...]
    tenant_recoverable_expense_share: tuple[float, ...]
    full_month_expense_recovery: tuple[float, ...]
    expense_recovery: tuple[float, ...]

    def __post_init__(self) -> None:
        expected = len(self.months)
        for name, series in (
            (
                "economic_responsibility_factor",
                self.economic_responsibility_factor,
            ),
            (
                "tenant_recoverable_expense_share",
                self.tenant_recoverable_expense_share,
            ),
            (
                "full_month_expense_recovery",
                self.full_month_expense_recovery,
            ),
            ("expense_recovery", self.expense_recovery),
        ):
            if len(series) != expected:
                raise ValueError(
                    f"LeaseRecoverySchedule requires one {name} figure per "
                    f"model month; got {len(series)} for {expected} months."
                )
