"""Gate AM1 -- Managed Assets and Monthly Performance.

The post-acquisition layer: an approved acquisition becomes a Managed Asset,
and each month's approved budget is compared against what actually happened.

Authorized by ``docs/architecture/AM1_MANAGED_ASSETS_MONTHLY_PERFORMANCE.md``.

This package performs every AM1 financial calculation and imports no
acquisition, Scenario, Strategy, Capital Structure, Partnership or AI module: a
Managed Asset is not a Deal, and monthly reporting can never reach -- or change
-- an underwriting result.
"""

from .contracts import (
    MONETARY_FIELDS,
    OPERATING_EXPENSE_FIELDS,
    REVENUE_FIELDS,
    Assessment,
    AssetPerformanceResult,
    AssetReportIssue,
    AssetReportIssueCode,
    AssetReportValidationError,
    AttentionItem,
    BudgetImmutableError,
    FinancialLine,
    LineVariance,
    ManagedAsset,
    ManagedAssetExistsError,
    ManagedAssetNotFoundError,
    MonthlyAssetReport,
    MonthlyReportExistsError,
    MonthlyReportNotFoundError,
    NoiTrendPoint,
    OperatingFigures,
    PeriodPerformance,
    PeriodTotals,
    UnitOfMeasure,
    VarianceDirection,
)
from .performance import (
    LINE_LABELS,
    VARIANCE_TOLERANCE,
    analyze_asset_performance,
    analyze_month,
    attention_items,
    cash_flow_after_capex,
    line_variance,
    net_cash_flow,
    net_operating_income,
    noi_margin,
    noi_trend,
    period_totals,
    total_operating_expenses,
    total_revenue,
    variance_pct,
    year_to_date_reports,
)
from .validation import (
    MAX_COMMENTARY_LENGTH,
    MAX_NAME_LENGTH,
    normalize_reporting_month,
    require_valid_managed_asset,
    require_valid_monthly_report,
    validate_figures,
    validate_managed_asset,
    validate_monthly_report,
)

__all__ = [
    "LINE_LABELS",
    "MAX_COMMENTARY_LENGTH",
    "MAX_NAME_LENGTH",
    "MONETARY_FIELDS",
    "OPERATING_EXPENSE_FIELDS",
    "REVENUE_FIELDS",
    "VARIANCE_TOLERANCE",
    "Assessment",
    "AssetPerformanceResult",
    "AssetReportIssue",
    "AssetReportIssueCode",
    "AssetReportValidationError",
    "AttentionItem",
    "BudgetImmutableError",
    "FinancialLine",
    "LineVariance",
    "ManagedAsset",
    "ManagedAssetExistsError",
    "ManagedAssetNotFoundError",
    "MonthlyAssetReport",
    "MonthlyReportExistsError",
    "MonthlyReportNotFoundError",
    "NoiTrendPoint",
    "OperatingFigures",
    "PeriodPerformance",
    "PeriodTotals",
    "UnitOfMeasure",
    "VarianceDirection",
    "analyze_asset_performance",
    "analyze_month",
    "attention_items",
    "cash_flow_after_capex",
    "line_variance",
    "net_cash_flow",
    "net_operating_income",
    "noi_margin",
    "noi_trend",
    "normalize_reporting_month",
    "period_totals",
    "require_valid_managed_asset",
    "require_valid_monthly_report",
    "total_operating_expenses",
    "total_revenue",
    "validate_figures",
    "validate_managed_asset",
    "validate_monthly_report",
    "variance_pct",
    "year_to_date_reports",
]
