/** Gate AM1 -- the authorized demo case as the API returns it.
 *
 * The exact figures from
 * `docs/architecture/AM1_MANAGED_ASSETS_MONTHLY_PERFORMANCE.md` Section 9,
 * computed by the Python engine and pasted here as the response shape. The
 * frontend tests assert against these values, so a component that started
 * calculating something of its own would disagree with the engine and fail.
 */

import type {
  AssetPerformanceResponse,
  ManagedAsset,
  MonthlyAssetReport,
  OperatingFigures,
} from './assetManagementTypes';

export const DEMO_BUDGET: OperatingFigures = {
  occupancy: 0.95,
  rental_revenue: 100000,
  other_income: 5000,
  property_taxes: 10000,
  insurance: 5000,
  utilities: 5000,
  repairs_and_maintenance: 6000,
  payroll: 6000,
  management_fees: 4000,
  other_operating_expenses: 2000,
  capital_expenditures: 10000,
  debt_service: 32500,
};

export const DEMO_ACTUAL: OperatingFigures = {
  occupancy: 0.925,
  rental_revenue: 96000,
  other_income: 6500,
  property_taxes: 10000,
  insurance: 5000,
  utilities: 6000,
  repairs_and_maintenance: 8000,
  payroll: 6000,
  management_fees: 4000,
  other_operating_expenses: 2000,
  capital_expenditures: 10000,
  debt_service: 32500,
};

export const DEMO_COMMENTARY =
  'Two renewals moved into April. Repairs were elevated by an unplanned HVAC replacement.';

export const DEMO_ASSET: ManagedAsset = {
  id: 'asset-1',
  source_deal_id: 'deal-1',
  name: 'Harbor Point Apartments',
  acquisition_date: '2026-10-01',
  property_type: 'Multifamily',
  market: 'Toronto, ON',
  acquisition_fingerprint: 'a1b2c3d4e5f6',
  created_at: '2027-03-01T00:00:00+00:00',
  updated_at: '2027-03-31T00:00:00+00:00',
};

export const DEMO_REPORT: MonthlyAssetReport = {
  managed_asset_id: 'asset-1',
  reporting_month: '2027-03-01',
  budget: DEMO_BUDGET,
  actual: DEMO_ACTUAL,
  commentary: DEMO_COMMENTARY,
  created_at: '2027-03-31T00:00:00+00:00',
  updated_at: '2027-03-31T00:00:00+00:00',
};

/** The March 2027 performance response, exactly as the engine produces it. */
export const DEMO_PERFORMANCE: AssetPerformanceResponse = {
  managed_asset: DEMO_ASSET,
  reported_months: ['2027-03-01'],
  result: {
    managed_asset_id: 'asset-1',
    reporting_month: '2027-03-01',
    commentary: DEMO_COMMENTARY,
    year_to_date_months: 1,
    noi_trend: [
      {
        reporting_month: '2027-03-01',
        budget_net_operating_income: 67000,
        actual_net_operating_income: 61500,
      },
    ],
    monthly: {
      budget: {
        total_revenue: 105000,
        total_operating_expenses: 38000,
        net_operating_income: 67000,
        cash_flow_after_capex: 57000,
        net_cash_flow: 24500,
        noi_margin: 0.6380952380952382,
      },
      actual: {
        total_revenue: 102500,
        total_operating_expenses: 41000,
        net_operating_income: 61500,
        cash_flow_after_capex: 51500,
        net_cash_flow: 19000,
        noi_margin: 0.6,
      },
      lines: [
        {
          line: 'occupancy',
          unit: 'percent',
          direction: 'higher_is_favorable',
          budget: 0.95,
          actual: 0.925,
          variance: -0.024999999999999911,
          variance_pct: -0.026315789473684116,
          variance_points: -2.4999999999999911,
          assessment: 'unfavorable',
        },
        {
          line: 'rental_revenue',
          unit: 'currency',
          direction: 'higher_is_favorable',
          budget: 100000,
          actual: 96000,
          variance: -4000,
          variance_pct: -0.04,
          variance_points: null,
          assessment: 'unfavorable',
        },
        {
          line: 'other_income',
          unit: 'currency',
          direction: 'higher_is_favorable',
          budget: 5000,
          actual: 6500,
          variance: 1500,
          variance_pct: 0.3,
          variance_points: null,
          assessment: 'favorable',
        },
        {
          line: 'total_revenue',
          unit: 'currency',
          direction: 'higher_is_favorable',
          budget: 105000,
          actual: 102500,
          variance: -2500,
          variance_pct: -0.023809523809523808,
          variance_points: null,
          assessment: 'unfavorable',
        },
        {
          line: 'property_taxes',
          unit: 'currency',
          direction: 'lower_is_favorable',
          budget: 10000,
          actual: 10000,
          variance: 0,
          variance_pct: 0,
          variance_points: null,
          assessment: 'on_plan',
        },
        {
          line: 'insurance',
          unit: 'currency',
          direction: 'lower_is_favorable',
          budget: 5000,
          actual: 5000,
          variance: 0,
          variance_pct: 0,
          variance_points: null,
          assessment: 'on_plan',
        },
        {
          line: 'utilities',
          unit: 'currency',
          direction: 'lower_is_favorable',
          budget: 5000,
          actual: 6000,
          variance: 1000,
          variance_pct: 0.2,
          variance_points: null,
          assessment: 'unfavorable',
        },
        {
          line: 'repairs_and_maintenance',
          unit: 'currency',
          direction: 'lower_is_favorable',
          budget: 6000,
          actual: 8000,
          variance: 2000,
          variance_pct: 0.3333333333333333,
          variance_points: null,
          assessment: 'unfavorable',
        },
        {
          line: 'payroll',
          unit: 'currency',
          direction: 'lower_is_favorable',
          budget: 6000,
          actual: 6000,
          variance: 0,
          variance_pct: 0,
          variance_points: null,
          assessment: 'on_plan',
        },
        {
          line: 'management_fees',
          unit: 'currency',
          direction: 'lower_is_favorable',
          budget: 4000,
          actual: 4000,
          variance: 0,
          variance_pct: 0,
          variance_points: null,
          assessment: 'on_plan',
        },
        {
          line: 'other_operating_expenses',
          unit: 'currency',
          direction: 'lower_is_favorable',
          budget: 2000,
          actual: 2000,
          variance: 0,
          variance_pct: 0,
          variance_points: null,
          assessment: 'on_plan',
        },
        {
          line: 'total_operating_expenses',
          unit: 'currency',
          direction: 'lower_is_favorable',
          budget: 38000,
          actual: 41000,
          variance: 3000,
          variance_pct: 0.07894736842105263,
          variance_points: null,
          assessment: 'unfavorable',
        },
        {
          line: 'net_operating_income',
          unit: 'currency',
          direction: 'higher_is_favorable',
          budget: 67000,
          actual: 61500,
          variance: -5500,
          variance_pct: -0.08208955223880597,
          variance_points: null,
          assessment: 'unfavorable',
        },
        {
          line: 'capital_expenditures',
          unit: 'currency',
          direction: 'no_direction',
          budget: 10000,
          actual: 10000,
          variance: 0,
          variance_pct: 0,
          variance_points: null,
          assessment: 'neutral',
        },
        {
          line: 'cash_flow_after_capex',
          unit: 'currency',
          direction: 'no_direction',
          budget: 57000,
          actual: 51500,
          variance: -5500,
          variance_pct: -0.09649122807017543,
          variance_points: null,
          assessment: 'neutral',
        },
        {
          line: 'debt_service',
          unit: 'currency',
          direction: 'no_direction',
          budget: 32500,
          actual: 32500,
          variance: 0,
          variance_pct: 0,
          variance_points: null,
          assessment: 'neutral',
        },
        {
          line: 'net_cash_flow',
          unit: 'currency',
          direction: 'higher_is_favorable',
          budget: 24500,
          actual: 19000,
          variance: -5500,
          variance_pct: -0.22448979591836735,
          variance_points: null,
          assessment: 'unfavorable',
        },
      ],
      attention: [
        { line: 'occupancy', message: 'Occupancy is 2.5 pts below plan', assessment: 'unfavorable' },
        {
          line: 'rental_revenue',
          message: 'Rental Revenue is 4.0% below plan',
          assessment: 'unfavorable',
        },
        {
          line: 'total_revenue',
          message: 'Total Revenue is 2.4% below plan',
          assessment: 'unfavorable',
        },
        { line: 'utilities', message: 'Utilities is $1,000 over budget', assessment: 'unfavorable' },
        {
          line: 'repairs_and_maintenance',
          message: 'Repairs and Maintenance is $2,000 over budget',
          assessment: 'unfavorable',
        },
        {
          line: 'total_operating_expenses',
          message: 'Total Operating Expenses is $3,000 over budget',
          assessment: 'unfavorable',
        },
        {
          line: 'net_operating_income',
          message: 'Net Operating Income is 8.2% below plan',
          assessment: 'unfavorable',
        },
        {
          line: 'net_cash_flow',
          message: 'Net Cash Flow is 22.4% below plan',
          assessment: 'unfavorable',
        },
      ],
    },
    // One reported month, so the year to date equals the month -- except that
    // it carries no occupancy line at all.
    year_to_date: {
      budget: {
        total_revenue: 105000,
        total_operating_expenses: 38000,
        net_operating_income: 67000,
        cash_flow_after_capex: 57000,
        net_cash_flow: 24500,
        noi_margin: 0.6380952380952382,
      },
      actual: {
        total_revenue: 102500,
        total_operating_expenses: 41000,
        net_operating_income: 61500,
        cash_flow_after_capex: 51500,
        net_cash_flow: 19000,
        noi_margin: 0.6,
      },
      lines: [
        {
          line: 'total_revenue',
          unit: 'currency',
          direction: 'higher_is_favorable',
          budget: 105000,
          actual: 102500,
          variance: -2500,
          variance_pct: -0.023809523809523808,
          variance_points: null,
          assessment: 'unfavorable',
        },
        {
          line: 'total_operating_expenses',
          unit: 'currency',
          direction: 'lower_is_favorable',
          budget: 38000,
          actual: 41000,
          variance: 3000,
          variance_pct: 0.07894736842105263,
          variance_points: null,
          assessment: 'unfavorable',
        },
        {
          line: 'net_operating_income',
          unit: 'currency',
          direction: 'higher_is_favorable',
          budget: 67000,
          actual: 61500,
          variance: -5500,
          variance_pct: -0.08208955223880597,
          variance_points: null,
          assessment: 'unfavorable',
        },
        {
          line: 'net_cash_flow',
          unit: 'currency',
          direction: 'higher_is_favorable',
          budget: 24500,
          actual: 19000,
          variance: -5500,
          variance_pct: -0.22448979591836735,
          variance_points: null,
          assessment: 'unfavorable',
        },
      ],
      attention: [
        {
          line: 'net_operating_income',
          message: 'Net Operating Income is 8.2% below plan',
          assessment: 'unfavorable',
        },
      ],
    },
  },
};
